transforms:
  - name: handle_dummy_table
  - name: key_mapping
  - name: column_transform_chain
    config:
      transforms:
        - name: canonicalize_numeric
        - name: canonicalize_datetime
        - name: featurize_datetime
          config:
            methods:
              - TIMESTAMP
            retain_original: true
        #- name: glove_text_embedding
  - name: filter_column
    config:
      drop_dtypes:
        - text