transforms:
  - name: handle_dummy_table
  - name: key_mapping
  - name: column_transform_chain
    config:
      transforms:
        - name: canonicalize_numeric
        - name: canonicalize_datetime
        - name: featurize_datetime
          config:
            methods:
              - TIMESTAMP
              - YEAR
              - MONTH
              - DAY
              - DAYOFWEEK
            retain_original: true
        #- name: glove_text_embedding
        - name: remap_category
  - name: filter_column
    config:
      drop_dtypes:
        - text
  - name: fill_timestamp